### ISSUE TITLE
BE/08.01/이벤트 스토밍

### ISSUE THREAD

**Issue by Yunsik-Choi** [softeerbootcamp-2nd/A1-PoongCha#5]
- [x] Miro를 사용해 이벤트 스토밍 진행
  - [x] 도메인 이벤트 도출
  - [x] 타임라인 나열
  - [x] 고충점을 도출
  - [x] 중요 이벤트 식별
  - [x] 커맨드 도출
  - [x] 정책 설정
  - [x] 읽기 모델 식별
  - [x] 외부 시스템 식별
  - [x] 애그리게이트 식별
  - [x] 바운디드 컨텍스트 식별
  - [x] 컨텍스트 매핑

- [x] [Wiki](https://github.com/softeerbootcamp-2nd/A1-PoongCha/wiki/%EC%9D%B4%EB%B2%A4%ED%8A%B8-%EC%8A%A4%ED%86%A0%EB%B0%8D) 에 반영

**Comment by socra167** [comment]
정리해서 위키 반영 에정

**Comment by socra167** [comment]
- [ ] `옵션 변경` 정책 네이밍 수정 필요
